config/routes.rb
Rails.application.routes.draw do

  root to: "index#home"

  resources :user, only: [ :new, :create, :edit, :update ]

  get "signin", to: "sessions#new", as: "new_session"
  post "signin", to: "sessions#create", as: "create_session"
  delete "signout", to: "sessions#destroy", as: "destroy_session"

  get "horses/mine", to: "horses#mine", as: "my_horses"
  get "horses/:id/transfer", to: "horses#transfer", as: "transfer_horses"
  post "horses/:id/transfer", to: "horses#give", as: "give_horses"
  get "horses/:id/stable", to: "horses#stable", as: "stable_horses"
  post "horses/:id/stable", to: "horses#house", as: "house_horses"
  resources :horses, except: [:destroy]

  # get "stables/mine", to: "stables#mine", as: "my_stables"
  resources :stables do
    collection do
      get "mine", as: "my"
    end
  end

  get "shows/active", to: "shows#active", as: "active_shows"
  get "shows/mine", to: "shows#mine", as: "my_shows"
  resources :shows do
    resources :classes, shallow: true, controller: 'klasses', except: [:index] do
      member do
        post 'move_up'
        post 'move_down'
      end
      resources :requirements, shallow: true, except: [:index, :show]
      resources :entries, shallow: true, only: [:new, :create, :destroy]
    end
  end

end

app/controllers/horses_controller.rb
class HorsesController < ApplicationController
  include ApplicationHelper

  before_action :verify_login, except: [:show, :index]
  before_action :get_horse, only: [:edit, :update, :transfer, :give, :show, :stable, :house]

  def new
    @horse = Horse.new.decorate
    @stables = Stable.where(user_id: current_user.id).map { |stable| [stable.name, stable.id]}
  end

  def create
    @horse = Horse.new(horse_params)
    @horse.user_id = session[:user_id]
    if @horse.save
      redirect_to horse_url(@horse), notice: "Horse successfully created."
    else
      render :new
    end
  end

  def edit
    unless can? :edit, @horse
      redirect_to horse_url(@horse), notice: owner_notice("horse")
    end
  end

  def update
    if can? :update, @horse
      if @horse.update_attributes(horse_params)
        redirect_to horse_url(@horse), notice: "Successfully updated #{@horse.name}."
      else
        render :edit
      end
    else
      redirect_to horse_url(@horse), notice: owner_notice("horse")
    end
  end

  def show
  end

  def index
    @horses = Horse.all.decorate
  end

  def mine
    @horses = Horse.owned_by(current_user.id).decorate
  end

  def transfer
    unless can? :transfer, @horse
      redirect_to horse_url(@horse), notice: owner_notice("horse", "transfer")
    end
    @users = User.all.map { |u| [u.name, u.id] }
  end

  def give
    if can? :give,  @horse
      @new = User.find(params[:horse][:user_id])
      @horse.transfer(@new)
      @horse.save
      @notice = "Successfully transferred #{@horse.name} to #{@new.name}."
    else
      @notice = owner_notice("horse")
    end
    redirect_to horse_url(@horse), notice: @notice
  end

  def stable
    unless can? :edit, @horse
      redirect_to horses_url(@horse), notice: owner_notice("horse","restable")
    else
    end
  end

  def house
    unless can? :edit, @horse
      redirect_to horse_url(@horse), notice: owner_notice("horse","restable")
    else
      unless params[:horse][:stable_id] == nil
        @stable = Stable.find(params[:horse][:stable_id])
        @horse.house!(@stable)
        redirect_to horse_url(@horse), notice: "Successfully stabled #{@horse.name} at #{@stable.name}."
      else
        render :stable
      end
    end
  end

  private
  def horse_params
    params.require(:horse).permit(:name,:year,:color,:breed,:gender,:user_id,:stable_id)
  end

  def get_horse
    @horse = Horse.find(params[:id]).decorate
  end
end

app/views/horses/_list.html.haml
- @horses.each do |horse|
  %p
    = horse.link
    = " - #{horse.info}"

app/views/horses/edit.html.haml
= form_for @horse, action: :update do |f|
  = f.text_field :name
  = f.number_field :year
  = f.text_field :color
  = f.text_field :breed
  = f.select(:gender, Horse.genders.keys)
  = f.submit "Update Horse"
end

app/views/horses/index.html.haml
= render "list"

app/views/horses/mine.html.haml
= render "list"

app/views/horses/new.html.haml
= form_for @horse do |f|
  = render "shared/errors", object: @horse
  = f.text_field :name
  = f.number_field :year
  = f.text_field :color
  = f.text_field :breed
  = f.select(:gender, Horse.genders.keys)
  = f.select(:stable_id, @stables)
  = f.submit "Create Horse"
end

app/views/horses/show.html.haml
%h2= @horse.name
%p= @horse.info

app/views/horses/stable.html.haml
= form_for @horse, {url: house_horses_url(@horse), method: :post} do |f|
  = f.collection_select(:stable_id, Stable.where(user_id: current_user.id), :id, :name)
  = f.submit "Restable Horse"

app/views/horses/transfer.html.haml
= form_for @horse,{ url: give_horses_url(@horse), method: :post } do |f|
  = f.collection_select(:user_id, User.all, :id, :name)
  = f.submit "Transfer Horse"