config/routes.rb
Rails.application.routes.draw do

  root to: "index#home"

  resources :user, only: [ :new, :create, :edit, :update ]

  get "signin", to: "sessions#new", as: "new_session"
  post "signin", to: "sessions#create", as: "create_session"
  delete "signout", to: "sessions#destroy", as: "destroy_session"

  get "horses/mine", to: "horses#mine", as: "my_horses"
  get "horses/:id/transfer", to: "horses#transfer", as: "transfer_horses"
  post "horses/:id/transfer", to: "horses#give", as: "give_horses"
  get "horses/:id/stable", to: "horses#stable", as: "stable_horses"
  post "horses/:id/stable", to: "horses#house", as: "house_horses"
  resources :horses, except: [:destroy]

  # get "stables/mine", to: "stables#mine", as: "my_stables"
  resources :stables do
    collection do
      get "mine", as: "my"
    end
  end

  get "shows/active", to: "shows#active", as: "active_shows"
  get "shows/mine", to: "shows#mine", as: "my_shows"
  resources :shows do
    resources :classes, shallow: true, controller: 'klasses', except: [:index] do
      member do
        post 'move_up'
        post 'move_down'
      end
      resources :requirements, shallow: true, except: [:index, :show]
      resources :entries, shallow: true, only: [:new, :create, :destroy]
    end
  end

end

app/models/show.rb
class Show < ActiveRecord::Base

  include Ownable

  belongs_to :user
  belongs_to :stable
  has_many :klasses, -> {order(position: :asc)}, dependent: :destroy
  has_many :results, through: :klasses
  #TODO: add test for this

  after_create :create_job

  enum generator: %w(test standard)

  validates :user_id, presence: true
  validates :stable_id, presence: true
  validates :name, {presence: true, length: {within: (4..30)}}
  validates :held_at, {presence: true, date: true}
  validates :deadline, {presence: true, numericality: true}
  validates :generator, presence: true

  scope :active, -> { where("held_at > ?", DateTime.now) }

  def open?
    DateTime.now < held_at - deadline.seconds
  end

  def active?
    DateTime.now < held_at
  end

  def destructable?
    dest = active?
    if dest
      klasses.each do |klass|
        unless klass.destructable?
          dest = false
        end
      end
    end
    return dest
  end

  def conduct
    if self.results.count == 0
      klasses.each do |k|
        k.judge unless k.judged?
      end
    else
      false
    end
  end

  def create_job
    ShowsJob.set(wait_until: self.held_at).perform_later(self.id)
  end
end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController

  before_filter :verify_login
  before_filter :get_show, only: [:show, :edit, :update, :destroy]

  def index
    @shows = Show.all.decorate
  end

  def show

  end

  def new
    @show = Show.new.decorate
  end

  def create
    @show = Show.new(show_params)
    @show.user = current_user
    if @show.save
      redirect_to show_url(@show), notice: "Successfully created #{@show.name}."
    else
      render :new
    end
  end

  def edit
    unless can? :edit, @show
      redirect_to show_url(@show), notice: owner_notice("show")
    end
  end

  def update
    unless can? :update, @show
      redirect_to @show, notice: owner_notice("show")
    else
      if @show.update_attributes(show_params)
        redirect_to @show, notice: "Successfully updated #{@show.name}."
      else
        render :edit
      end
    end
  end

  def destroy
    if can? :destroy, @show
      if @show.destructable?
        @show.delete
        redirect_to shows_url, notice: "Successfully deleted show."
      else
        redirect_to @show, notice: "That show may not be destroyed."
      end
    else
      redirect_to @show, notice: owner_notice("show","delete")
    end
  end

  def mine
    @shows = Show.where(user_id: current_user.id)
  end

  def active
    @shows = Show.active
  end

  private
  def get_show
    @show = Show.find(params[:id]).decorate
  end

  def show_params
    params.require(:show).permit(:name,:description,:deadline,:held_at,:generator,:user_id,:user,:stable_id,:stable)
  end
end

app/views/shows/_form.html.haml
= form_for @show do |f|
  = render "shared/errors", object: @show
  = f.text_field :name
  = f.text_field :description
  = collection_select :show, :stable_id, Stable.where(user_id: current_user.id), :id, :name
  = datetime_select :show, :held_at
  = select(:show, :deadline, [["24 Hours", 24.hours], ["12 Hours", 12.hours]])
  = select(:show, :generator, [["Standard", "standard"]])
  = f.submit(action_name == "new" || action_name == "create" ? "Create Show" : "Update Show")

app/views/shows/_list.html.haml
- @shows.each do |show|
  %p= link_to show.name, show_url(show)

app/views/shows/active.html.haml
= render "list"

app/views/shows/edit.html.haml
= render "form"

app/views/shows/index.html.haml
= render "list"

app/views/shows/mine.html.haml
= render "list"

app/views/shows/new.html.haml
= render "form"

app/views/shows/show.html.haml
%h1= @show.name

= render "shared/manage_links", object: @show

%p= link_to "Add Class", new_show_class_url(@show)

#klasses
  - @show.klasses.each do |klass|
    %p
      = link_to klass.name, class_url(klass)
      = " - #{klass.level} #{klass.discipline} (#{klass.spots} spots available)"
      - if @show.owned_by?(current_user)
        = link_to "Edit Class", edit_class_url(klass)
        = link_to "Delete Class", class_url(klass), method: :delete
        = link_to("Move Up", move_up_class_url(klass), method: :post)
        = link_to("Move Down", move_down_class_url(klass), method: :post)