config/routes.rb
Rails.application.routes.draw do

  root to: "index#home"

  resources :user, only: [ :new, :create, :edit, :update ]

  get "signin", to: "sessions#new", as: "new_session"
  post "signin", to: "sessions#create", as: "create_session"
  delete "signout", to: "sessions#destroy", as: "destroy_session"

  get "horses/mine", to: "horses#mine", as: "my_horses"
  get "horses/:id/transfer", to: "horses#transfer", as: "transfer_horses"
  post "horses/:id/transfer", to: "horses#give", as: "give_horses"
  get "horses/:id/stable", to: "horses#stable", as: "stable_horses"
  post "horses/:id/stable", to: "horses#house", as: "house_horses"
  resources :horses, except: [:destroy]

  # get "stables/mine", to: "stables#mine", as: "my_stables"
  resources :stables do
    collection do
      get "mine", as: "my"
    end
  end

  get "shows/active", to: "shows#active", as: "active_shows"
  get "shows/mine", to: "shows#mine", as: "my_shows"
  resources :shows do
    resources :classes, shallow: true, controller: 'klasses', except: [:index] do
      member do
        post 'move_up'
        post 'move_down'
      end
      resources :requirements, shallow: true, except: [:index, :show]
      resources :entries, shallow: true, only: [:new, :create, :destroy]
    end
  end

end

app/controllers/klasses_controller.rb
 class KlassesController < ApplicationController

  before_filter :verify_login
  before_filter :get_klass, only: [:show, :edit, :update, :destroy, :move_up, :move_down]
  before_filter :get_show, only: [:new, :create]

  def show
  end

  def new
    if can? :edit, @show
      @klass = Klass.new.decorate
    else
      redirect_to show_url(@show), notice: owner_notice("show","add classes to")
    end
  end

  def create
    if can? :edit, @show
      @klass = Klass.new(klass_params)
      @klass.show = @show
      @klass.judged = false
      @klass.save
      redirect_to show_url(@show), notice: "Successfully created #{@klass.name}."
    else
      redirect_to show_url(@show), notice: owner_notice("show","add classes to")
    end
  end

  def edit
    unless can? :edit, @klass.show
      redirect_to show_url(@klass.show), notice: owner_notice("show","edit classes for")
    end
  end

  def update
    if can? :edit, @klass.show
      if @klass.update_attributes(klass_params)
        redirect_to show_url(@klass.show), notice: "Successfully updated #{@klass.name}."
      else
        render :edit
      end
    else
      redirect_to show_url(@klass.show), notice: owner_notice("show","edit classes for")
    end
  end

  def destroy
    unless can? :destroy, @klass
      redirect_to class_url(@klass)
    else
      if @klass.destructable?
        @klass.delete
        redirect_to show_url(@klass.show), notice: "Successfully deleted class."
      else
        redirect_to class_url(@klass), notice: "Could not delete class."
      end
    end
  end

  def move_up
    if can? :edit, @klass
      @klass.move_higher
      @notice = "Successfully reordered classes."
    else
      @notice = owner_notice("class","reorder")
    end
    redirect_to show_url(@klass.show), notice: @notice
  end

  def move_down
    if can? :edit, @klass
      @klass.move_lower
      @notice = "Successfully reordered classes."
    else
      @notice = owner_notice("class","reorder")
    end
    redirect_to show_url(@klass.show), notice: @notice
  end

  private
  def get_show
    @show = Show.find(params[:show_id]).decorate
  end

  def get_klass
    @klass = Klass.find(params[:id]).decorate
  end

  def klass_params
    params.require(:klass).permit(:name,:description,:discipline,:level,:entry_limit,:show,:show_id)
  end
end

app/views/klasses/_form.html.haml
= render 'shared/errors', object: @klass
= f.text_field :name
= f.text_field :discipline
= f.text_field :level
= f.number_field :entry_limit

app/views/klasses/edit.html.haml
= form_for(@klass, url: class_path(@klass), method: :put) do |f|
  = render "form", f: f
  = f.submit "Update Class"

app/views/klasses/new.html.haml
= form_for(@klass, url: show_classes_path(show_id: @show), method: :post) do |f|
  = render "form", f: f
  = f.submit "Create Class"

app/views/klasses/show.html.haml
%h2= @klass.name
%p= "#{@klass.level} #{@klass.discipline}"
%h3 Requirements
= link_to "Add Requirement", new_class_requirement_path(@klass)
- @klass.requirements.each do |r|
  %p= r.decorate.brief
  %p= link_to "Edit", edit_requirement_path(r)
  %p= link_to "Delete", requirement_path(r), method: :delete
%h3 Entries
- @klass.entries.each do |e|
  %p= e.horse.name
  - if e.horse.owned_by?(current_user)
    = link_to "Remove Entry", entry_path(e), method: :delete